### ISSUE TITLE
支持截图，粘贴吗？

### ISSUE THREAD

**Issue by rockmelodies** [ShareManT/laravel-admin-ext-editormd#2]
？

**Comment by ShermanTsang** [comment]
当前可以支持图片上传，只要配置好filesystem里面的配置。
目前不支持截图和粘贴，后续时间多会添加。

**Comment by Lruihao** [comment]
> 当前可以支持图片上传，只要配置好filesystem里面的配置。
> 目前不支持截图和粘贴，后续时间多会添加。

我的filesystem配置如下请问怎么实现图片上传功能呢
![image](https://user-images.githubusercontent.com/33419593/80270727-2f783680-86ed-11ea-99e3-14ab1b13ad5e.png)
![image](https://user-images.githubusercontent.com/33419593/80270747-5afb2100-86ed-11ea-9d6c-0f47fdcdf54f.png)
