### ISSUE TITLE
emoji 图像不能显示问题

### ISSUE THREAD

**Issue by gyp719** [ShareManT/laravel-admin-ext-editormd#3]
![image](https://user-images.githubusercontent.com/30563368/55693678-d7d43380-59e2-11e9-88c2-2e931609d98b.png)

即使我将 emoji 下载 在本地进行引用，也提示错误

**Comment by ShermanTsang** [comment]
Hi，你需要在项目的config/admin.php文件中设置editormd的emoji参数为true。
`emoji => true`

**Comment by ShermanTsang** [comment]
详细配置
```
'extensions' => [
    'editormd' => [
        // Set to false if you want to disable this extension
        'enable' => true,
	// Set to true if you want to take advantage the screen length for your editormd instance.
	'wideMode' => false,
	// Set to true when the instance included in larave-admin tab component.
	'dynamicMode' => false,
        // Editor configuration
        'config' => 
        [
	    'path' => '/vendor/laravel-admin-ext/editormd/editormd-1.5.0/lib/',
	    'width' => '100%',
            'height' => 600,
            'emoji' => true
        ]
    ]
]
```

**Comment by gyp719** [comment]
非常感谢！

**Comment by gyp719** [comment]
github emoji 图像不显示，我将 emoji下载至本地的 plugins/emoji-dialog 目录下，但是 本地的emoji  并没有起作用  
![image](https://user-images.githubusercontent.com/30563368/55695217-2c2ee180-59ea-11e9-9d27-904740453899.png)
![image](https://user-images.githubusercontent.com/30563368/55695223-3224c280-59ea-11e9-9a0e-ddaebef8117b.png)

**Comment by gyp719** [comment]
![image](https://user-images.githubusercontent.com/30563368/55695269-6c8e5f80-59ea-11e9-95c1-8d0adf389b74.png)

此处也进行了修改

**Comment by ShermanTsang** [comment]
这个主要问题在于下面这个地址被GFW拦住了。
http://www.emoji-cheat-sheet.com/
你单独修改 editormd.js 是不行的，因为考虑到速度原因，我默认用的是editormd.min.js
![image](https://user-images.githubusercontent.com/4065724/55812784-2f2aee80-5b1e-11e9-97ec-41dd4e95037a.png)

关于editormd相关的配置你需要写在，config/admin.php 配置中的 extensions -> editormd -> config 中，这样才会把配置加载到实例上。

**Comment by gyp719** [comment]
再次 请将下，我 具体的应该 如何 去配置？

**Comment by gyp719** [comment]
修改 editormd.min.js  里面 的读取 本地的 emoji 地址 可以解决

**Comment by ShermanTsang** [comment]
> 修改 editormd.min.js 里面 的读取 本地的 emoji 地址 可以解决

解决了就好哟
